---
title: "SuperAged"
author: "박성종,박호관,이선애,장근희"
date: '2020 2 14 '
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 인구 피라미드 
```{r Human Pyramid}
library(gganimate)
library(gifski)
library(png)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(readxl)
datPop <- data.table::fread('material/population.csv', encoding='UTF-8')
datPop2 <- read_excel('material/2021~2023.xls')
datPop3 <- read_excel('material/2050.xlsx')

datPopAni <- datPop %>% mutate(year=as.integer(year)) %>% gather(key='gender', value='population', male, female)
datPop2Ani <- datPop2 %>% mutate(year=as.integer(year)) %>% gather(key='gender', value='population', male, female)
datPop3Ani <- datPop3 %>% mutate(year=as.integer(year)) %>% gather(key='gender', value='population', male, female)

datPopAni <- subset(datPopAni,select=-age)
datPop4Ani <- rbind(datPopAni,datPop2Ani)
datPop5Ani <- rbind(datPop4Ani,datPop3Ani)

ggplot(datPop5Ani, aes(x=age2, 
                       y=ifelse(gender=='male', 
                                population/10000, -population/10000), fill=gender)) +
  geom_bar(stat='identity') +
  geom_bar(stat='identity', width=0.9,alpha=0.8) +
  scale_x_continuous(name='나이') +
  scale_y_continuous(name='인구(만명)', labels=c(50, 25, 0, 25, 50)) + 
  coord_flip() +
  labs(title = '한국의 인구 변화 ({frame_time} 년)')+
  scale_fill_manual(name='성별', labels=c('여', '남'), values=c('#FF33CC', 'dodgerblue2'))+
  theme_minimal() +
  theme(legend.position='bottom', title=element_text(size=16)) + 
  theme(legend.position='bottom') +
  transition_time(year) + 
  enter_fade() -> p
p


```

##노인복지시설 수
```{r ## 노인복지시설 수 }
library(readxl)
library(dplyr)
library(ggplot2)
# ========== 데이터 준비 ========== 
# 엑셀 읽기
pac <- read_xlsx("material/노인복지생활시설수.xlsx")
# 데이터 전처리
pacdata <-  as.data.frame(pac)
pacdata <- rename(pacdata, cnt = "춧")
# ========== 데이터타입 변경 ========== 
# place 변수는 그래프에서 x축에 출력된다. 
# 이때 place 변수명은 자동으로 가나다순으로 정렬된다. 
# place 변수가 팩터형일 경우에는 자동으로 정렬되지 않는다. 
# 따라서 place 변수의 데이터타입을 팩터형으로 변경한다.
# place 변수 데이터타입 변경
#   - 문자형 -> 팩터형
pacdata$place <- as.factor(pacdata$place)
# 데이터 확인
#   - 레벨 순서에 의해 변수 내용이 화면에 출력된다.
#   - 레벨이 원하는 순서인지 확인한다.
pacdata$place
# 레벨 순서 설정
#   - 원하는 순서대로 레벨 순서를 변경한다.
pacdata$place <- 
  factor(pacdata$place, levels = c("노인주거복지시설", "노인의료복지시설", "노인여가복지시설", "재가노인복지시설"))
# 데이터 확인
#   - 원하는 순서대로 레벨 순서가 변경되었다.
pacdata$place
# ========== 그래프  ========== 
# 그래프 작성
# 그래프 색상 변경
#   - 조건에 맞게 그래프 색상을 변경한다.
ggplot(pacdata, aes(x=place, y=cnt)) + 
  geom_col( fill = ifelse(pacdata$cnt >= 10000, "orange", 
                                  ifelse(pacdata$cnt >= 5000, "dodgerblue2",
                                         ifelse(pacdata$cnt >= 1000, "dodgerblue", "darkorange")))) +
  xlab('노인복지시설') + ylab('인원') +
  theme_bw()+ scale_y_continuous(breaks=seq(0,100000,5000)) 
```


##복지시설 실태
```{r 복지시설실태}
area<-read_excel("material/실태.xlsx")
ggplot(data = area, aes(x =facilities, y =수용인원 )) +
  geom_col(fill="dodgerblue2")+                                             #색깔지정
  scale_y_continuous(breaks=seq(10000,2700000,250000))+                     #칸 수
  ggtitle('복지시설과 이용자 수')+ theme_bw()+                              # theme_bw 사각형
  ylab("수용인원") + xlab("시설")+
  theme(plot.title = element_text(                                          #타이틀 지정
    face="bold",
    hjust=0.5,
    vjust=1,
    size=20,
    color="#FF6600"))+
  geom_line(data = area,color="orange",size=1.5, aes(x =facilities, y = 사용인원 , group = 1,))+
  geom_point(data = area,color="orange",size=3, aes(x =facilities, y = 사용인원 , group = 1)) +
  theme(legend.position = "top")

```
##재가 실 사용자 


```{r 재가 실 사용자 그래프}
grade <- read_excel('material/등급별.xlsx')
as.data.frame(grade)


# 불필요한 부분 지우기 
grade1 <- subset(grade,select=-qualify)


# melt
grade_result <- melt(grade1,id.vars='area')


# ggplot,geom_bar 를 이용하여 그래프로 나타내기 
ratio <- ggplot(grade_result,aes(x=area,y=value,fill=variable))
ratio + geom_bar(stat='identity',position = 'dodge') + scale_fill_manual(name='', labels=c('재가 대상자', '실제 이용자'), values=c('darkorange', 'dodgerblue2')) +xlab('지역') + ylab('비율') +theme_bw()+scale_y_continuous(breaks=seq(0,25,1))
```

